export const projects = [
    {
        "id": "1",
        "creatorId": "1",
        "name": "Poverty in Africa",
        "currentPrice": 5000,
        "targetPrice": 10000,
        "donationCount": 20,
        "description": "This is a charity project with the aim of building a community library for children in African countries",
        "category": "Poverty",
        "image": "https://images.unsplash.com/photo-1635929114944-8bab23b98e74?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1234&q=80",
        "isFeatured": true,
        "createAt": "2022-10-12", 
    },
    {
        "id": "2",
        "creatorId": "1",
        "name": "Public libraries for children in Africa",
        "currentPrice": 350,
        "targetPrice": 10000,
        "donationCount": 40,
        "description": "This is a charity project with the aim of building a community library for children in African countries",
        "category": "Education",
        "image": "https://images.unsplash.com/photo-1658611694395-60e62e5353f3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
        "isFeatured": false,
        "createAt": "2022-10-15", 
    },
    {
        "id": "3",
        "creatorId": "2",
        "name": "Donate for Homeless People",
        "currentPrice": 80,
        "targetPrice": 3000,
        "donationCount": 23,
        "description": "This is a charity project with the aim of building a community library for children in African countries",
        "category": "Homelessness",
        "image": "https://images.unsplash.com/photo-1518398046578-8cca57782e17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        "isFeatured": true,
        "createAt": "2022-10-15", 
    },
    {
        "id": "4",
        "creatorId": "2",
        "name": "Food Donation",
        "currentPrice": 5000,
        "targetPrice": 5000,
        "donationCount": 345,
        "description": "One million people in the Netherlands live below the poverty line. Will you help us hand out food surpluses and by doing so prevent food waste.\n“An eye for food, a heart for people”\nNearly one million people in the Netherlands live below the poverty line. Did you know that this dire situation can be solved simply by giving food surpluses? A solution both good for people and the environment.\nEvery week our food bank volunteers hand out food to those who need it most. Companies, institutions, governments and individuals offer their support through funds, food, and services.\nThroughout the Netherlands, our volunteers show up with passion and dedication for their work in the food banks. Though we are tremendously grateful for the support and care of our sponsors, helping people in the food banks is very expensive. The funds are used for logistics, transportation and gasoline, and storage rent. For as little as $5 you can help a family eat for seven days.\nYour donation is solely for the people who need it most. No one in the food bank receives a salary. We only work with volunteers. Support the food bank with your donation.\nWill you join us too?",
        "category": "Food Banks",
        "image": "https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        "isFeatured": true,
        "createAt": "2022-10-17", 
    },
    {
        "id": "5",
        "creatorId": "1",
        "name": "Community School",
        "currentPrice": 0,
        "targetPrice": 2500,
        "donationCount": 10,
        "description": "This is a charity project with the aim of building a community school for children in Africa",
        "category": "Education",
        "image": "https://images.unsplash.com/photo-1473649085228-583485e6e4d7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80",
        "isFeatured": false,
        "createAt": "2022-10-20", 
    },
    {
        "id": "6",
        "creatorId": "2",
        "name": "Homeless People in the UK",
        "currentPrice": 800,
        "targetPrice": 7500,
        "donationCount": 138,
        "description": "This is a charity project with the aim of helping homeless people in the UK",
        "category": "Homelessness",
        "image": "https://images.unsplash.com/photo-1542367787-4baf35f3037d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        "isFeatured": false,
        "createAt": "2022-10-23", 
    },
    {
        "id": "7",
        "creatorId": "2",
        "name": "Vaccine in Covid-19",
        "currentPrice": 8000,
        "targetPrice": 15000,
        "donationCount": 590,
        "description": "This is a charity project with the aim of helping people vaccinated through pandemic",
        "category": "Health & Medical",
        "image": "https://images.unsplash.com/photo-1605289982774-9a6fef564df8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
        "isFeatured": false,
        "createAt": "2022-10-31", 
    },
    {
        "id": "8",
        "creatorId": "1",
        "name": "Free Clean Water for African",
        "currentPrice": 1300,
        "targetPrice": 7000,
        "donationCount": 98,
        "description": "This is a charity project with the aim of giving free water for African",
        "category": "Food Banks",
        "image": "https://images.unsplash.com/photo-1574482620826-40685ca5ebd2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
        "isFeatured": true,
        "createAt": "2022-11-03", 
    },
    {
        "id": "9",
        "creatorId": "2",
        "name": "Free Face Mask through Pandemic",
        "currentPrice": 2000,
        "targetPrice": 3000,
        "donationCount": 0,
        "description": "Wearing a mask is a critical way to prevent the spread of COVID-19. Masks and respirators, when worn consistently and correctly, are effective at reducing the transmission of SARS-CoV-2, the virus that causes COVID-19. Free N95 masks are available to pick up at local pharmacies and community health center sites across the country. Every person is allowed up to 3 free masks pending availability.",
        "category": "Health & Medical",
        "image": "https://images.unsplash.com/photo-1599493347474-7e864c18489e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        "isFeatured": true,
        "createAt": "2022-11-05", 
    },
    {
        "id": "10",
        "creatorId": "2",
        "name": "Building schools for ethnic minorities in Vietnam",
        "currentPrice": 17864,
        "targetPrice": 30000,
        "donationCount": 3642,
        "description": "Wearing a mask is a critical way to prevent the spread of COVID-19. Masks and respirators, when worn consistently and correctly, are effective at reducing the transmission of SARS-CoV-2, the virus that causes COVID-19. Free N95 masks are available to pick up at local pharmacies and community health center sites across the country. Every person is allowed up to 3 free masks pending availability.",
        "category": "Education",
        "image": "https://images.unsplash.com/photo-1598690419800-8100e015ff2c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        "isFeatured": true,
        "createAt": "2022-11-06", 
    },
]

export const users = [
    {
        "id": "1",
        "email": "19521862@gm.uit.edu.vn",
        "name": "The Team 01 Charity - Vietnam 1st Charity site for helping the community for the better world",
        "avatar": "https://i.pinimg.com/originals/83/95/aa/8395aa28f2c034d4b944187ea973aecd.jpg",
        "coverBackground": "https://i.pinimg.com/originals/b0/c8/35/b0c8353d633f719a6cf45d21bc938b95.jpg",
        "description": "4th year student at the University of Information Technology",
        "phoneNumber": "0123456789",
        "facebook": "https://www.facebook.com/",
        "twitter": "https://twitter.com/",
        "createAt": "2022-10-30"
    },
    {
        "id": "2",
        "email": "19521862@gm.uit.edu.vn",
        "name": "iammy 🐰",
        "avatar": "https://i.pinimg.com/originals/b1/a0/a5/b1a0a59261b607cd0ccd78a8428ca295.jpg",
        "coverBackground": "https://i.pinimg.com/originals/ae/44/01/ae4401dc31a173fe879260d111341a1c.jpg",
        "description": "Love pink and hate lies",
        "phoneNumber": "0123456789",
        "facebook": "https://www.facebook.com/iammy204",
        "twitter": "",
        "createAt": "2022-11-03"
    },
]